trigger:
  branches:
    include:
    - main

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureSubscription'
        scriptType: 'bash'
        scriptPath: 'deploy-arm-template.sh'
