BEGIN TRANSACTION;

BEGIN TRY
    ALTER TABLE Customers ADD COLUMN NewColumn VARCHAR(50);
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'Error detected, rollback applied';
END CATCH;
